# fluent-bit 구성 정보 -> 설정 -> 작동
# ---------------------
# 서비스 정의, 전역 설정
# 로그 1개당 전송, 전송과정에 대한 로그는 info 레벨만 확인
# ---------------------
[SERVICE]
    Flush           1
    Log_Level       info
    Parsers_File    /fluent-bit/etc/parsers.conf

# ---------------------
# 입력 (로그 수집) -> 2개 (xx_json.log, xx_text.log)
# ---------------------
[INPUT]
    Name              tail
    Path              /opt/airflow/sensor_logs/sensor_json.log
    Tag               sensor.json
    Parser            json
    DB                /fluent-bit/state/sensor-json.db
    DB.Sync           Normal
    Refresh_Interval  1
    Rotate_Wait       5
    Skip_Long_Lines   On

    # macOS Docker bind mount에서는 inotify 대신 stat polling 사용
    Inotify_Watcher   false

# ---------------------
# 출력 (로그 전송) -> 2개(실제 전달, kafka(json), logstash(text)) + 2개(모니터링용, 임시 편성)
# ---------------------
[OUTPUT]
    Name        stdout
    Match       sensor.json