input {
    # http 5044번 입력
    http {
        port => 5044
    }
}
filter {
    # Grok이라는 도구를 이용하여 비정형 데이터 => 반정형 데이터 변환 처리
    if [message] =~ "ID=" {
        grok {
            match => { "message" => "\[%{TIMESTAMP_ISO8601:log_time}\] ID=%{DATA:device_id} \|   TEMP:%{NUMBER:temp:float} \|   HUMI:%{NUMBER:humi:float} \|   STAT:%{WORD:status}" }
        }
    }
}
output {
    # Kafka 브로커 전달 (9092)
}